### PR TITLE
exit, pause and restart

### PR DESCRIPTION
**Pull request by elkassimyhajar**

### CODE REVIEW

**Review by chqirsamia — APPROVED** [review]

**Review by chqirsamia — CHANGES_REQUESTED** [review]
i think you should remove the .classpath and .project files

**Comment by elkassimyhajar** [comment]
@chqirsamia @fimtow Yes I see but when using a .gitignore file that discards those two files, is it necessary to remove them?

**Comment by fimtow** [comment]
> @chqirsamia @fimtow Yes I see but when using a .gitignore file that discards those two files, is it necessary to remove them?

Yes, you need to remove them manually because you already added them. Adding them to the `.gitignore` file will only untrack any new changes to these files.

**Review by AJOthmane — APPROVED** [review]

**Review by fimtow — CHANGES_REQUESTED** [review]
The pause menu shows up only one time. If you paused the game another time, it doesn't show up.

**Comment by elkassimyhajar** [comment]
Yes I programmed it so as to show up only once. It seemed somehow annoying to have the same dialog pop up every time the player pauses the game especially when they know what they have to do afterwards.

**Review by chqirsamia — APPROVED** [review]

**Review by fimtow — APPROVED** [review]
shipit :shipit:

**Pull request merged**
