### PR TITLE
add menu start

### PR DESCRIPTION
**Pull request by chqirsamia**

### CODE REVIEW

**Comment by AJOthmane** [comment]
can you tell us why you changed the classpath file?

**Comment by chqirsamia** [comment]
> can you tell us why you changed the classpath file?

I didn't modify it, it was added automatically

**Review by fimtow — CHANGES_REQUESTED** [review]
You should not commit the `.classpath` and `.projet` files. You either remove them manually using `git rm` or use the `.gitignore` file. We've already made one so you can just pull from the develop branch.

**Comment by chqirsamia** [comment]
> You should not commit the `.classpath` and `.projet` files. You either remove them manually using `git rm` or use the `.gitignore` file. We've already made one so you can just pull from the develop branch.

done

**Review by fimtow — CHANGES_REQUESTED** [review]
I can't change the background 😕. When clicking _change the player_ nothing happens.

**Comment by chqirsamia** [comment]
> I can't change the background 😕. When clicking _change the player_ nothing happens.

if you want to change the background click on the letter B on your keyboard a window displaying the existing backgrounds is displayed once the background has been chosen, you close the window and enter the corresponding number

**Comment by chqirsamia** [comment]
> I can't change the background 😕. When clicking _change the player_ nothing happens.

if you want to change the background click on the letter "c" on your keyboard a window displaying the existing backgrounds is displayed once the background has been chosen you close the window and enter the corresponding number

**Comment by fimtow** [comment]
> > I can't change the background 😕. When clicking _change the player_ nothing happens.
> 
> if you want to change the background click on the letter B on your keyboard a window displaying the existing backgrounds is displayed once the background has been chosen, you close the window and enter the corresponding number

I doesn't seem to work

**Review by fimtow — CHANGES_REQUESTED** [review]
* Background isn't showing correctly (see image below)
* Game crashes when player dies (if you changed background, if not it doesn't) (see log below)
* Isn't there a better way to show the available backgrounds, opening a new window just to show the available backgrounds is a little bit messy.

image

```
 [java] java.io.FileNotFoundException: maps\map0.txt (The system cannot find the file specified)
     [java]     at java.base/java.io.FileInputStream.open0(Native Method)
     [java]     at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
     [java]     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
     [java]     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
     [java]     at java.base/java.io.FileReader.<init>(FileReader.java:60)
     [java]     at com.TETOSOFT.tilegame.MapLoader.loadMap(MapLoader.java:139)
     [java]     at com.TETOSOFT.tilegame.MapLoader.reloadMap(MapLoader.java:121)
     [java]     at com.TETOSOFT.tilegame.GameEngine.update(GameEngine.java:367)
     [java]     at com.TETOSOFT.test.GameCore.gameLoop(GameCore.java:151)
     [java]     at com.TETOSOFT.test.GameCore.run(GameCore.java:80)
     [java]     at com.TETOSOFT.tilegame.GameEngine.main(GameEngine.java:24)
     [java] Exception in thread "main" java.lang.NullPointerException
     [java]     at com.TETOSOFT.tilegame.TileMapDrawer.draw(TileMapDrawer.java:82)
     [java]     at com.TETOSOFT.tilegame.GameEngine.draw(GameEngine.java:245)
     [java]     at com.TETOSOFT.test.GameCore.gameLoop(GameCore.java:155)
     [java]     at com.TETOSOFT.test.GameCore.run(GameCore.java:80)
     [java]     at com.TETOSOFT.tilegame.GameEngine.main(GameEngine.java:24)
```

**Comment by chqirsamia** [comment]
> * Background isn't showing correctly (see image below)
> * Game crashes when player dies (if you changed background, if not it doesn't) (see log below)
> * Isn't there a better way to show the available backgrounds, opening a new window just to show the available backgrounds is a little bit messy.
> 
> image
> 
> ```
>  [java] java.io.FileNotFoundException: maps\map0.txt (The system cannot find the file specified)
>      [java]     at java.base/java.io.FileInputStream.open0(Native Method)
>      [java]     at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
>      [java]     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
>      [java]     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
>      [java]     at java.base/java.io.FileReader.<init>(FileReader.java:60)
>      [java]     at com.TETOSOFT.tilegame.MapLoader.loadMap(MapLoader.java:139)
>      [java]     at com.TETOSOFT.tilegame.MapLoader.reloadMap(MapLoader.java:121)
>      [java]     at com.TETOSOFT.tilegame.GameEngine.update(GameEngine.java:367)
>      [java]     at com.TETOSOFT.test.GameCore.gameLoop(GameCore.java:151)
>      [java]     at com.TETOSOFT.test.GameCore.run(GameCore.java:80)
>      [java]     at com.TETOSOFT.tilegame.GameEngine.main(GameEngine.java:24)
>      [java] Exception in thread "main" java.lang.NullPointerException
>      [java]     at com.TETOSOFT.tilegame.TileMapDrawer.draw(TileMapDrawer.java:82)
>      [java]     at com.TETOSOFT.tilegame.GameEngine.draw(GameEngine.java:245)
>      [java]     at com.TETOSOFT.test.GameCore.gameLoop(GameCore.java:155)
>      [java]     at com.TETOSOFT.test.GameCore.run(GameCore.java:80)
>      [java]     at com.TETOSOFT.tilegame.GameEngine.main(GameEngine.java:24)
> ```

1-I solved the problem with the background (the size of the image did not match the size I wanted) the quality of the image is not good, but it does the trick
2-i think it's resolved
3-it is the method that seemed to me to be simple and effective

**Pull request merged**
